microservice:
  name: grade-submission-api
  namespace: grade-submission
  replicas: 2

workload:
  image: rslim087/kubernetes-course-grade-submission-api:stateless-v4
  port: 3000
  livenessDelay: 15
  resource:
    memory: '128Mi'
    cpu: '200m'

env:
  MONGODB_HOST: mongodb
  MONGODB_PORT: '27017'

secrets:
  MONGODB_URI: 'mongodb://mongodb.mongodb.svc.cluster.local:27017'
